In [4]:
import math

In [52]:
import numpy

In [14]:
#Abbiamo una lista di liste:
#mat = [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]
#Che tipo di struttura dati o matematica potrebbe rappresentare?
#Notare che tutte le liste "interne" sono della stessa dimensione Come facciamo per accedere ad un elemento in particolare?
mat = [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]
mat [1] [2] #per prendere devi dirgli quale numero vuoi dalla lista più grande e poi da quella più piccola

7

In [ ]:
#Importiamo il modulo math e proviamo a usare le funzioni .sin() .cos() .factorial() e la variabile .pi la riconoscete?

In [ ]:
#Proviamo a eseguire math.degrees(math.pi) Qual è e cosa significa il risultato? Per saperne di più su questa funzione possiamo usare help(math.degrees)

In [32]:
#L'azienda Object SpA ha creato una lista di quanti oggetti ha venduto ogni mese nell'ultimo anno:
#lst = [2000, 5500, 7200, 4320, 1280, 1900, 2500, 3900, 6410, 8150, 7100, 5350]
#trasformiamola in un array NumPy (casting): lst = np.array(lst) e rispondiamo alle domande del CEO della Object SpA:
#qual è stata la vendita massima mensile? E quella minima?
#quali sono le vendite mensili maggiori di 4999 oggetti? E quante ne sono?
#quali sono le vendite minori di 3000 oggetti? 
#in media quanti oggetti sono stati venduti al mese?
lst = [2000, 5500, 7200, 4320, 1280, 1900, 2500, 3900, 6410, 8150, 7100, 5350]
lst = numpy.array(lst)
lst.min()

1280

In [34]:
lst.max()

8150

In [38]:
filtro = lst > 4999
vendite_grandi = lst[filtro]
print (vendite_grandi)

[5500 7200 6410 8150 7100 5350]


In [42]:
filtro3k = lst < 3000
piccole_vendite = lst[filtro3k]
print (piccole_vendite)

[2000 1280 1900 2500]


In [44]:
lst.mean()

4634.166666666667

In [ ]:
#Consideriamo il seguente dizionario:
#fatturati_dict = {1997: 12_000, 1998: 15_000, 1999: 20_000, 2000: 23_000, 2001: 25_000, 2002: 17_000, 2003: 14_000, 2004: 21_000}
#Consideriamo ora la seguente Series: fatturati_series = pd.Series([12_000, 15_000, 20_000, 23_000, 25_000, 17_000, 14_000, 21_000] index=range(1997, 2005))
#Possiamo accedere alle stesse informazioni nello stesso modo: fatturati_dict[1997] fatturati_series[1997]
#Dunque qual è la differenza tra i due tipi di dato?
#Cosa potremmo fare con la Series che non possiamo fare con il dizionario?

In [48]:
#L'azienda Object SpA ha un dataset con tutti gli stipendi dei dipendenti, memorizzato in un ndarray:
#import numpy as np stipendi = np.array( [100, 200, 300, 400, 500,  600, 700, 800, 900, 1000] )
#L'azienda ci chiede di raddoppiare tutti gli stipendi; facciamolo in due modi:
#con un ciclo for 7
#con il masking
stipendi = numpy.array( [100, 200, 300, 400, 500,  600, 700, 800, 900, 1000] )

In [50]:
stipendi * 2

array([ 200,  400,  600,  800, 1000, 1200, 1400, 1600, 1800, 2000])